// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Ch5eZuQxsgUf7yBk1lpJF1EwuRF8Xno',
    appId: '1:373799435278:web:50eec4c301c0d3a746505f',
    messagingSenderId: '373799435278',
    projectId: 'note-app-71351',
    authDomain: 'note-app-71351.firebaseapp.com',
    storageBucket: 'note-app-71351.firebasestorage.app',
    measurementId: 'G-6HQ0781X2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPBQPxS62hvdl93NTGC-oU-SS9smgRKAU',
    appId: '1:373799435278:android:e6cd5714a7cee55046505f',
    messagingSenderId: '373799435278',
    projectId: 'note-app-71351',
    storageBucket: 'note-app-71351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCbNt0CaADo2XTz0YmHiIqwOmSUK2CfY',
    appId: '1:373799435278:ios:0f5d95aea060016046505f',
    messagingSenderId: '373799435278',
    projectId: 'note-app-71351',
    storageBucket: 'note-app-71351.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCbNt0CaADo2XTz0YmHiIqwOmSUK2CfY',
    appId: '1:373799435278:ios:0f5d95aea060016046505f',
    messagingSenderId: '373799435278',
    projectId: 'note-app-71351',
    storageBucket: 'note-app-71351.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Ch5eZuQxsgUf7yBk1lpJF1EwuRF8Xno',
    appId: '1:373799435278:web:56866b40103d6a5a46505f',
    messagingSenderId: '373799435278',
    projectId: 'note-app-71351',
    authDomain: 'note-app-71351.firebaseapp.com',
    storageBucket: 'note-app-71351.firebasestorage.app',
    measurementId: 'G-JKY9Y05DDS',
  );
}
